version: '3.8'

services:
  service-resep:
    build:
      context: ./service-resep
    container_name: service-resep
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root@mysql:3307/db_resep 
      - PORT=3000
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3307:3306" 
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
