version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_resep
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  service-resep:
    image: service-resep
    build:
      context: ./service-resep
    container_name: service-resep
    ports:
      - "3000:3000"
    env_file:
      - service-resep/.env
    depends_on:
      - mysql
    restart: always


volumes:
  mysql-data:
